import { test, expect } from '@playwright/test'

test('custom cursor stays centered on the pointer across hover sizes and scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  async function checkCenter(x: number, y: number) {
    x = Math.round(x)
    y = Math.round(y)
    await page.mouse.move(x, y)
    await expect.poll(() => page.evaluate(({ x, y }) => {
      return Math.max(...['cursor-dot', 'cursor-outline'].map(id => {
        const rect = document.getElementById(id)!.getBoundingClientRect()
        return Math.max(Math.abs(rect.x + rect.width / 2 - x), Math.abs(rect.y + rect.height / 2 - y))
      }))
    }, { x, y })).toBeLessThan(0.75)
  }
  await checkCenter(200, 160)
  const button = await page.locator('a[href="#work"]').last().boundingBox()
  await checkCenter(button!.x + button!.width / 2, button!.y + button!.height / 2)
  await expect(page.locator('body')).toHaveClass(/hovering/)
  await expect.poll(async () => (await page.locator('#cursor-outline').boundingBox())!.width).toBeCloseTo(90, 0)
  await checkCenter(200, 160)
  await page.locator('.project-card-stack').first().scrollIntoViewIfNeeded()
  const project = await page.locator('.mission-img-box').first().boundingBox()
  await checkCenter(project!.x + project!.width / 2, project!.y + project!.height / 2)
  await expect(page.locator('body')).toHaveClass(/view-project/)
  await expect.poll(async () => (await page.locator('#cursor-outline').boundingBox())!.width).toBeCloseTo(120, 0)
  await page.evaluate(() => document.body.classList.add('god-mode'))
  await checkCenter(180, 150)
})

test('desktop portfolio loads without runtime errors and all images resolve', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (/Portfolio effects|[Hh]ydration/.test(message.text())) errors.push(message.text())
  })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  await expect(page.locator('h1')).toContainText('BUILD')
  await expect(page).toHaveTitle('Aditya Dwi Saputra Nugraha | Software Developer')
  await expect(page.locator('#about')).toContainText('Aditya Dwi Saputra Nugraha')
  await expect(page.locator('#magnetic-btn')).toContainText('dheep.co@gmail.com')
  await expect(page.locator('#experience')).toContainText('PT Traspac Makmur Sejahtera')
  await expect(page.locator('.public-project-card')).toHaveCount(2)
  await expect(page.locator('.project-overview')).toHaveCount(3)
  await expect(page.locator('.project-card-stack')).toHaveCount(3)
  await expect(page.locator('.tagcloud-item')).toHaveCount(11)
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.fonts.check('700 48px Syncopate'))).toBeTruthy()
  for (const img of await page.locator('img').all()) {
    const src = await img.getAttribute('src')
    const response = await request.get(src!)
    expect(response.ok()).toBeTruthy()
    expect(response.headers()['content-type']).toContain('image/')
  }
  await expect(page.locator('a[href$=".pdf"]')).toHaveCount(0)
  await expect(page.locator('.public-project-link[href="https://github.com/DhitGT/secret-message"]')).toBeAttached()
  await expect(page.locator('.public-project-link[href="https://www.dheep.site/1945/"]')).toBeAttached()
  await expect(page.locator('body')).not.toContainText('SHIVAM')
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  expect(errors).toEqual([])
})

test('mobile navigation opens, closes, and scrolls to selected section', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  const button = page.getByRole('button', { name: 'Toggle navigation' })
  await button.click()
  await expect(button).toHaveAttribute('aria-expanded', 'true')
  await page.locator('.mobile-link[href="#loadout"]').click()
  await expect(button).toHaveAttribute('aria-expanded', 'false')
  await expect(page).toHaveURL(/#loadout$/)
  await expect(page.locator('#loadout')).toBeInViewport()
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
})

test('physics playground supports gravity, adding skills, and reset', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  await page.locator('#playground').scrollIntoViewIfNeeded()
  await expect(page.locator('#physics-canvas canvas')).toBeVisible({ timeout: 15000 })
  await page.locator('#phy-gravity').click()
  await expect(page.locator('#phy-gravity')).toHaveText('GRAVITY: OFF')
  await page.locator('#phy-add').click()
  await page.locator('#phy-restart').click()
  await page.locator('#phy-gravity').click()
  await expect(page.locator('#phy-gravity')).toHaveText('GRAVITY: ON')
})

test('contact form sends a message through Nuxt to Laravel', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  await page.locator('#contact').scrollIntoViewIfNeeded()
  await page.getByLabel('Name', { exact: true }).fill('Browser Test Visitor')
  await page.getByLabel('Email', { exact: true }).fill('browser-test@example.com')
  await page.getByLabel('Message', { exact: true }).fill('End-to-end test of the Nuxt and Laravel contact form.')
  const result = page.waitForResponse(response => response.url().endsWith('/api/contact') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'SEND TRANSMISSION' }).click()
  expect((await result).status()).toBe(201)
  await expect(page.locator('form [role="status"]')).toContainText('TRANSMISSION RECEIVED')
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('')
})

test('reduced motion still shows the content and a readable skill sphere', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  await expect(page.locator('.tagcloud-item')).toHaveCount(11)
  await expect(page.locator('h1')).toBeVisible()
})

test('failed contact service never reports success and preserves the draft', async ({ page }) => {
  await page.route('**/api/contact', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"message":"Contact service unavailable."}' }))
  await page.goto('/')
  await expect(page.locator('#loader')).toBeHidden({ timeout: 15000 })
  await page.locator('#contact').scrollIntoViewIfNeeded()
  await page.getByLabel('Name', { exact: true }).fill('Offline Visitor')
  await page.getByLabel('Email', { exact: true }).fill('offline@example.com')
  await page.getByLabel('Message', { exact: true }).fill('This draft should stay available when the API is offline.')
  await page.getByRole('button', { name: 'SEND TRANSMISSION' }).click()
  await expect(page.locator('form [role="status"]')).toContainText('Connection unavailable')
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('Offline Visitor')
})
